# Generated by Django 5.0.4 on 2024-04-13 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_task_delete_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="image",
            field=models.ImageField(default="", upload_to="images/"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="task",
            name="prompt",
            field=models.CharField(default="mann", max_length=100),
            preserve_default=False,
        ),
    ]
