# Generated by Django 5.0.4 on 2024-04-14 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_task_image_task_prompt"),
    ]

    operations = [
        migrations.RenameField(
            model_name="task",
            old_name="content",
            new_name="description",
        ),
    ]
