# Generated by Django 5.0.4 on 2024-04-16 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_rename_content_task_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="annotated_image",
            field=models.ImageField(default={}, upload_to="images/"),
            preserve_default=False,
        ),
    ]
