# Generated by Django 5.0.4 on 2024-04-16 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_task_annotated_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="annotated_data",
            field=models.TextField(default="{mann:mann}"),
            preserve_default=False,
        ),
    ]
